{% set version = "3.0.1" %}

package:
  name: opt-einsum
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/opt_einsum/opt_einsum-{{ version }}.tar.gz
  sha256: 8aba07af4cf80e86ec57a0fcc0d36267a37e15a19fbdcf8734ed836e04defea9

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.7

test:
  imports:
    - opt_einsum
    - opt_einsum.backends
    - opt_einsum.tests

about:
  home: https://github.com/dgasmith/opt_einsum
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Optimizing numpys einsum function"

extra:
  recipe-maintainers:
    - ocefpaf
